version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: social_user
      POSTGRES_PASSWORD: social_password
      POSTGRES_DB: social_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - app-network
volumes:
  postgres_data:
networks:
  app-network:
    driver: bridge